CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP;
DROP TABLE DEPT_TEMP;

CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP
(DEPTNO, DNAME, LOC)
VALUES (50, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP
VALUES(60, 'JAVA', 'BUSAN');

SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP
(LOC, DNAME, DEPTNO)
VALUES ('INCHEON', 'HTML', 90);

SELECT * FROM DEPT_TEMP;


INSERT INTO DEPT_TEMP
VALUES(70, 'WEB', NULL); --LOC : NULL

SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP
(DEPTNO, LOC) --DNAME : NULL
VALUES(80, 'BUCHEON');

SELECT * FROM DEPT_TEMP;


CREATE TABLE EMP_TEMP
AS SELECT *
    FROM EMP
    WHERE 1<>1;
    
SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(1111, '코난', 'POLICE', NULL, '2021/01/01', 5000, 1000, 10);

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(2222, '장미', 'Science', 9999, '2020/12/01', 4000, 2000, 20);

SELECT * FROM EMP_TEMP;

--TO_DATE를 사용해 날짜 정보 입력하기
INSERT INTO EMP_TEMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(3333, '미란', 'ANALYST', 5555, TO_DATE('08/08/18', 'DD/MM/YYYY'), 4000, 2000, 20);

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(4444, '키드', 'KID', '7777', TO_DATE('12/03/21', 'DD/MM/YYYY'), 5000, 1000, 30);

SELECT * FROM EMP_TEMP;


INSERT INTO EMP_TEMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

-- UPDATE문
CREATE TABLE DEPT_TEMP2
    AS SELECT * FROM DEPT;
    
SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'; --데이터 전체 수정하기

SELECT * FROM DEPT_TEMP2;

--ROLLBACK ; : 수정한 내용륻 되돌리고 싶은 경우

ROLLBACK;

SELECT * FROM DEPT_TEMP2;

-- 일부만 수정
UPDATE DEPT_TEMP2
SET 
DNAME = 'DATABASE',
LOC = 'SEOUL'
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

-- 서브쿼리를 통해 데이터 수정(UPDATE)

UPDATE DEPT_TEMP2
SET(DNAME, LOC) = (SELECT DNAME, LOC
                    FROM DEPT
                    WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
SET DNAME = (SELECT DNAME
            FROM DEPT
            WHERE DEPTNO = 40),
            LOC = (SELECT LOC
                    FROM DEPT
                    WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

--WHERE절에서 서브쿼리 사용

UPDATE DEPT_TEMP2
SET LOC='SEOUL'
WHERE DEPTNO IN (SELECT DEPTNO
                    FROM DEPT_TEMP2
                    WHERE DNAME = 'OPERATIONS');
                    
SELECT * FROM DEPT_TEMP2;


-- EMP_TEMP 테이블의 사원들 중 급여가 2500이하인 사원들만 추가수당을 50으로 수정
SELECT * FROM EMP_TEMP;

UPDATE EMP_TEMP
SET
COMM = 50;

SELECT * FROM EMP_TEMP;


CREATE TABLE EMP_TEMP2
    AS SELECT * FROM EMP;
    
SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2
WHERE EMPNO IN (SELECT E.EMPNO
                FROM EMP_TEMP2 E, SALGRADE S
                WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                AND S.GRADE = 3
                AND DEPTNO = 30);
                
SELECT * FROM EMP_TEMP2;

---EMP_TEMP 테이블에서 급여가 3000이상인 사원 삭제
SELECT * FROM EMP_TEMP;

DELETE FROM EMP_TEMP
WHERE SAL >= 3000;

SELECT * FROM EMP_TEMP;

--EMP_TEMP2에 있는 모든 데이터 삭제
SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2;

SELECT * FROM EMP_TEMP2;


----------------------------------
--연습문제
CREATE TABLE EX_EMP AS SELECT * FROM EMP;
CREATE TABLE EX_DEPT AS SELECT * FROM DEPT;
CREATE TABLE EX_SALGRADE AS SELECT * FROM SALGRADE;


----EX_DEPT 테이블에 60~90번 부서 등록하기(수정 O : COMMIT, 수정 X : ROLLBACK)
SELECT * FROM EX_DEPT;

INSERT INTO EX_DEPT(DEPTNO, DNAME, LOC) --????
SELECT D.DEPTNO, D.DNAME, D.LOC
FROM DEPT D
WHERE D.DEPTNO BETWEEN 60 AND 90;

SELECT * FROM EX_DEPT;

---- EX_EMP 테이블에서 새로운 데이터 추가하기(EMPNO 8001 ~ 8008 삽입
SELECT * FROM EX_EMP;


INSERT INTO EX_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
FROM EMP E
WHERE E.EMPNO BETWEEN 8001 AND 8008; --???

SELECT * FROM EX_EMP;

-- 60번 부서에서 근무하는 사원들의 평균 급여보다 많은 급여를 받고 있는
-- 사원들을 70번 부서로 옮기기(6행 업데이트)

UPDATE EX_EMP SET DEPTNO = 70 --???
WHERE SAL > (SELECT AVG(SAL) FROM EX_EMP
                GROUP BY DEPTNO
                HAVING DEPTNO = 60);


-- 60번 부서에서 근무하는 사원 중 입사일이 가장 빠른 사원보다
--늦게 입사한 사원의 급여를 10% 인사하고 70번 부서로 옮기기(6행)

UPDATE EX_EMP SET SAL = SAL*1.1, DEPTNO = 70
WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM EX_EMP
                    GROUP BY DEPTNO
                    HAVING DEPTNO = 60); --????
                    


---EX_EMP에 속한 사원 중 급여 등급이 5인 사원 삭제하기
SELECT * FROM EX_EMP;

DELETE FROM EX_EMP 
WHERE EMPNO IN (SELECT E.EMPNO
                 FROM EX_EMP E, EX_SALGRADE S
                  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                   AND S.GRADE = 5); 

SELECT * FROM EX_EMP;


------------------CREATE
CREATE TABLE EMP_DDL(
EMPNO   NUMBER(4),
ENAME   VARCHAR2(10),
JOB     VARCHAR2(9),
MGR     NUMBER(4),
HIREDATE  DATE,
SAL     NUMBER(7,2),
COMM    NUMBER(7,2),
DEPTNO  NUMBER(2)
);

DESC EMP_DDL; --DDL값 확인

CREATE TABLE DEPT_DDL
AS SELECT * FROM DEPT;

DESC DEPT_DDL;

CREATE TABLE EMP_DDL_30
AS SELECT *
    FROM EMP
    WHERE DEPTNO = 30;
    
DESC EMP_DDL_30;
SELECT * FROM EMP_DDL_30;

CREATE TABLE EMPDEPT_DDL
AS SELECT
    E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
    E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
    WHERE 1<>1;
    
DESC EMPDDL_DDL;
SELECT * FROM EMPDDL_DDL;


--------------ALTER
CREATE TABLE EMP_ALTER
AS SELECT * FROM EMP;

DESC EMP_ALTER;

ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

DESC EMP_ALTER;

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL; --열 이름 변경

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(10); --열 속성 바꿈

DESC EMP_ALTER;
SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
DROP COLUMN TEL; --특정 열을 삭제함

DESC EMP_ALTER;

RENAME EMP_ALTER TO EMP_RENAME; -- 테이블 이름 변경

DESC EMP_RENAME;

TRUNCATE TABLE EMP_RENAME; --모든 데이터 삭제(인스턴스), DELETE는 되돌기기가 가능하나 TRUNCATE는 되돌릴 수 X

DESC EMP_RENAME;
SELECT * FROM EMP_RENAME;

DROP TABLE EMP_RENAME; -- 테이블 삭제


--- 다음의 열 구조를 가지는 EMP_EX 테이블 생성하기

CREATE TABLE EMP_EX(
EMPNO   NUMBER(4),
ENAME   VARCHAR2(10),
JOB     VARCHAR2(9),
MGR     NUMBER(4),
HIREDATE  DATE,
SAL     NUMBER(7,2),
COMM    NUMBER(7,2),
DEPTNO  NUMBER(2)
);

-- 테이블에 BIGO(가변형 문자열, 길이 20) 추가

ALTER TABLE EMP_EX
ADD BIGO VARCHAR2(20);

DESC EMP_EX;

-- BIGO열 크기를 30으로 변경

ALTER TABLE EMP_EX
MODIFY BIGO VARCHAR2(30);

DESC EMP_EX;

-- BIGO열 이름을 비고로 변경

ALTER TABLE EMP_EX
RENAME COLUMN BIGO TO 비고;

DESC EMP_EX;

SELECT * FROM EMP_EX;

-- EMP_EX 테이블에 EMP테이블 데이터를 모두 저장하기(비고열은 NULL) -> 확인
--> 서브쿼리 이용하기
-- 테이블은 준비됨 -> INSERT만 함(P.8, 원하는 데이터 꺼내와서 다시하기)

SELECT * FROM EMP;

INSERT INTO EMP_EX
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, 
NULL FROM EMP;

SELECT * FROM EMP_EX;

