-- 등가 조인
SELECT EMPNO, ENAME, E.DEPTNO, DNAME, LOC
FROM EMP E, DEPT D
WHERE E. DEPTNO = D. DEPTNO
ORDER BY EMPNO;

-- 사원번호, 이름, 급여, 근무 부서와 함께 출력하되 급여가 3000이상인 데이터만 출력하기
SELECT
E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND SAL >= 3000;

-- SALGREADE 테이블과 EMP 연결
SELECT *
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

-- 자체 조인(하나의 테이블을 여러 개의 테이블처럼 사용)
SELECT 
E.EMPNO, E.ENAME, E.MGR,
M.EMPNO AS MGR_NO,
M.ENAME AS MGR_NAME
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO;

-- 외부 조인(왼쪽 외부 조인)
SELECT 
E.EMPNO, E.ENAME, E.MGR,
M.EMPNO AS MGR_NO,
M.ENAME AS MGR_NAME
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO(+)
ORDER BY E.EMPNO;

-- 외부 조인(오른쪽 외부 조인)
SELECT
E.EMPNO, E.ENAME, E.MGR,
M.EMPNO AS MGR_NO,
M.ENAME AS MGR_NAME
FROM EMP E, EMP M
WHERE E.MGR(+) = M.EMPNO
ORDER BY E.EMPNO;

-- NATUAL JOIN : 두 테이블에서 이름과 자료형이 같은 열 찾은 후 그 열을 기준으로 등가 조인
SELECT
E.EMPNO, E.ENAME, E.JOB, E.MGR,
E.HIREDATE, E.SAL, E.COMM,
DEPTNO,
D.DNAME, D.LOC
FROM EMP E NATURAL JOIN DEPT D
ORDER BY DEPTNO, E.EMPNO;

-- JOIN~USING 
-- 급여가 3000 이상인 사원들의 정보와 근무 부서 정보 출력하기
SELECT 
E.EMPNO, E.ENAME, E.JOB, E.MGR,
E.HIREDATE, E.SAL, E.COMM,
DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D USING(DEPTNO)
WHERE SAL>=3000
ORDER BY DEPTNO, E.EMPNO;

-- JOIN ~ ON
SELECT 
E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL,
E.COMM,
E.DEPTNO,
D.DNAME, D.LOC
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE SAL >= 3000
ORDER BY E.DEPTNO, EMPNO;

--OUTER JOIN
SELECT 
E.EMPNO, E.ENAME, E.MGR,
M.EMPNO AS MGR_NO,
M.ENAME AS MGR_NAME
FROM EMP E LEFT OUTER JOIN EMP M ON(E.MGR = M.EMPNO)
ORDER BY E.EMPNO;

SELECT
E.EMPNO, E.ENAME, E.MGR,
M.EMPNO AS MGR_NO,
M.ENAME AS MGR_NAME
FROM EMP E RIGHT OUTER JOIN EMP M ON(E.MGR = M.EMPNO)
ORDER BY E.EMPNO;