CREATE TABLE TEMP (
    COL1 VARCHAR(20),
    COR2 VARCHAR(20)
);

-- GLOBAL에 권한 부여
GRANT SELECT , INSERT
ON TEMP
TO C##GLOBAL;

--GLOBAL에 권한 회수
REVOKE SELECT, INSERT
ON TEMP
FROM C##GLOBAL;

SELECT * FROM EMP;

---------------------------PL/SQL