--커서(원하는 값 추출)

CREATE TABLE JOB (
EMPNO NUMBER(4),
ENAME VARCHAR2(10),
JOB VARCHAR2(10),
DEPTNO NUMBER(2)
);
 
INSERT INTO JOB (EMPNO, ENAME, JOB, DEPTNO)
VALUES(001, '한여진', '경찰', 24);
 
INSERT INTO JOB (EMPNO, ENAME, JOB, DEPTNO)
VALUES(002, '황시목', '검사', 37);
 
INSERT INTO JOB (EMPNO, ENAME, JOB, DEPTNO)
VALUES(003, '강원철', '검사', 50);
 
INSERT INTO JOB (EMPNO, ENAME, JOB, DEPTNO)
VALUES(004, '장건', '경찰', 22);
 
INSERT INTO JOB (EMPNO, ENAME, JOB, DEPTNO)
VALUES(005, '이연재', 'CEO', 80);
 
SELECT * FROM JOB;

--커서 예시
DECLARE 
    CNT1 NUMBER;
    CNT2 NUMBER;
BEGIN
    SELECT COUNT(*) INTO CNT1
    FROM EMP
    WHERE DEPTNO = 30;
    
    CNT2 := SQL%ROWCOUNT; --묵시적 커서
    
    DBMS_OUTPUT.PUT_LINE('CNT1의 값 : ' || CNT1);
    DBMS_OUTPUT.PUT_LINE('CNT2의 값 : ' || CNT2);
    END;

--커서 생성 : 1개 값만 나옴
DECLARE 
    V_ENME VARCHAR2(30);
    V_JOB VARCHAR2(30);
    CURSOR CUR_JOB IS SELECT ENAME, JOB FROM JOB;
BEGIN
    OPEN CUR_JOB;
    FETCH CUR_JOB INTO V_ENAME, V_JOB;
    DBMS_OUTPUT.PUT_LINE(V_ENAME || V_JOB);
    CLOSE CUR_JOB;
END;

--커서 생성(여러 값 나옴)
DECLARE 
     V_ENAME VARCHAR2(50);
    V_JOB VARCHAR2(50);
    CURSOR CUR_JOB IS SELECT ENAME, JOB FROM JOB;
BEGIN 
    OPEN CUR_JOB;
    LOOP
    FETCH CUR_JOB INTO V_ENAME, VJOB;
    IF CUR_JOB%NOTFOUND THEN
            EXIT;
    END IF;
    DBMS_OUTPUT.PUT_LINE(V_ENAME || V_JOB);
    END LOOP;
    CLOSE CUR_JOB;
END;