-- 데이터 사전

--scott 계정에서 사용 가능한 데이터 사전
SELECT * FROM DICTIONARY
WHERE TABLE_NAME LIKE 'USER_%';

-- 현재 오라클에 접속해 있는 사용자가 소유한 객체 정보 보관
SELECT TABLE_NAME
FROM USER_TABLES;

-- 현재 오라클에 접속해 있는 사용자가 소유한 객체 및 
--다른 사용자가 소유한 객체 중 사용이 허락되어 있는 객체 종류
SELECT OWNER, TABLE_NAME
FROM ALL_TABLES;

--SYSTEM 계정으로 DBA_ 접두어 사용함
SELECT * FROM DBA_TABLES;

--SYSTEM 계정으로 사용자 정보 살펴보기
SELECT *
FROM DBA_USERS
WHERE USERNAME = 'SCOTT';

-- 사용자가 직접 특정 테이블의 열 지정 가능하나, 기본키또는 고유키일 경우 자동 생성
SELECT * FROM USER_INDEXES;

-- EMP 테이블의 SAL 열에 인덱스 생성하기
CREATE INDEX IDX_BOOK_PRICE
ON BOOK(PRICE);

-- 생성된 인덱스 조회하기
SELECT * FROM USER_IND_COLUMNS;

-- 인덱스 삭제하기
DROP INDEX IDX_BOOK_PRICE;

-- 뷰 생성하기
CREATE VIEW VW_EMP20
AS (SELECT EMPNO, ENAME, JOB, DEPTNO
    FROM EMP
    WHERE DEPTNO = 20);
    
SELECT * FROM VW_EMP20;

-- EMP 테이블에서 SAL 기준으로 정렬하여 ROWNUM과 같이 출력하기
WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC) -- WITH E AS : 인라인 뷰
SELECT ROWNUM, E.*
FROM EMP E;

--  급여가 높은 상위 세 명 데이터 출력하기
WITH E AS(SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM, E.*
FROM EMP E
WHERE ROWNUM <= 3;

-- DEPT테이브로가 열 구성은 같고 데이터는 없는 테이블 생성
CREATE TABLE DEPT_SEQUENCE2
    AS SELECT * FROM DEPT
    WHERE 1<>1;
    
SELECT * FROM DEPT_SEQUENCE2;

--15씩 증가하는 SEQUENCE 생성
CREATE SEQUENCE SEQ_DEPT_SEQUENCE2
INCREMENT BY 15
START WITH 0
MAXVALUE 140
MINVALUE 0
NOCYCLE
CACHE 2;

SELECT * FROM USER_SEQUENCES;

-- NEXTVAL, CURRVAL 
SELECT SEQ_DEPT_SEQUNCE.CURRVAL
FROM DUAL;

INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'INCHEON');

ALTER SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 5
MAXVALUE 200
CYCLE;

SELECT * FROM USER_SEQUENCES;