CREATE USER C##GLOBAL
            IDENTIFIED BY ORACLE;
            
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE
TO C##GLOBAL;

--사용자 권한 부여


CREATE USER C##TESTER
            IDENTIFIED BY Tester;
            
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE
TO C##TESTER;