--입사일자가 81/04/02 보다 늦고 82/12/09 보다 빠른 사원의 이름, 월급, 부서 번호를 출력
SELECT ENAME AS "사원의 이름", SAL AS "월급", DEPTNO AS "부서번호"
FROM EMP
WHERE HIREDATE BETWEEN '81/04/02' AND '82/12/09';

--사원번호와 사원이름, 사원의 상관을 출력
SELECT E.EMPNO AS "사원번호", E.ENAME AS "사원이름", 
M.ENAME AS "사원의 상관"
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO;

--EMP 테이블의 기본키를 삭제하기 위해 필요한 명령어를 작성하시오. 단 기본키에 대한 제약 이름은 PK_EMP이다
ALTER TABLE EMP DROP CONSTRAINT PK_EMP;



--의사 테이블을 생성하는 SQL 문을 작성하시오.
-- DOCID는 기본키
-- 소속 속성의 값을 입력하지 않으면 자동으로 내과가 지정
-- 근무연수는 1년 이상 40년 이하 범위의 값을 가지도록 지정
CREATE TABLE DOCTORS (
DOCID VARCHAR(20) PRIMARY KEY,
DNAME VARCHAR(20),
DEPT VARCHAR(20) DEFAULT '내과',
WORKYEARS NUMBER CHECK(WORKYEARS>=1 AND WORKYEARS<=40)
);

INSERT INTO DOCTORS
VALUES('D001', '유명한', '내과',5);
INSERT INTO DOCTORS
VALUES('D002', '나애리', '정형외과', 15);

SELECT * FROM DOCTORS;

--환자 테이블을 생성하는 SQL 문을 작성하시오.
-- PATID는 기본키
-- 이름 속성은 널 값이 허용되지 않음
--담당의사 속성을 의사 테이블의 의사번호 속성을 참조하는 외래키로 지정

CREATE TABLE PATIENTS (
PATID VARCHAR(20) PRIMARY KEY,
PNAME VARCHAR(20) NOT NULL,
AGE NUMBER,
DOC VARCHAR(20),
FOREIGN KEY (DOC)
REFERENCES DOCTORS(DOCID) ON DELETE CASCADE
);
SELECT * FROM DOCTORS;
SELECT * FROM PATIENTS;

INSERT INTO PATIENTS 
VALUES('P001', '코난', 10, 'D002');
INSERT INTO PATIENTS 
VALUES('P002', '장미', 17, 'D002');

CREATE TABLE EX1 (
ID NUMBER,
NAME VARCHAR(20),
ZIP NUMBER,
REGDATE DATE
);

INSERT INTO EX1 
VALUES(11, '코난', 11111, '11/01/03');
INSERT INTO EX1 
VALUES(22, '장미', 22222, NULL);
INSERT INTO EX1 
VALUES(33, '미란', 3333, '15/02/03');
INSERT INTO EX1 
VALUES(44, '키드', 44444, NULL);

SELECT * FROM EX1;

ALTER TABLE EX1
MODIFY REGDATE DEFAULT SYSDATE NOT NULL, 
ZIP NOT NULL;