CREATE USER C##COFFEE IDENTIFIED BY "1234";

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE
TO C##COFFEE;

SELECT * FROM SCOTT.TEMP;

INSERT INTO SCOTT.TEMP
VALUES('TEXT', 'FROMCOFFEE');

INSERT INTO SCOTT.TEMP
VALUES('TEXT2', 'FROMCOFFEE2');

SELECT * FROM SCOTT.TEMP;

CREATE USER C##Tester IDENTIFIED BY Tester;