SELECT * FROM Employees;

SELECT EMPLOYEE_ID, LAST_NAME, EMAIL, HIRE_DATE
FROM Employees;

SELECT ALL FIRST_NAME, PHONE_NUMBER FROM Employees;

SELECT DISTINCT FIRST_NAME FROM Employees;

SELECT DISTINCT LAST_NAME, HIRE_DATE FROM Employees;

SELECT * FROM Employees;

SELECT JOB_ID, SALARY, SALARY*12+SALARY*0.005 AS "¿¬ºÀ 5%ÀÎ»ó"
FROM Employees;

SELECT SALARY FROM Employees
ORDER BY SALARY DESC;

SELECT * FROM Employees
WHERE department_id = 100;

SELECT * FROM Employees
WHERE DEPARTMENT_ID >= 50 AND MANAGER_ID >= 100;

SELECT * FROM Employees
WHERE DEPARTMENT_ID = 30 OR MANAGER_ID = 108;

SELECT * FROM Employees
WHERE SALARY != 5000;

SELECT * FROM Employees
WHERE SALARY <> 5000;

SELECT * FROM Employees
WHERE JOB_ID
IN ('IT_PROG, FI_ACCOUNT, ST_MAN');

SELECT * FROM Employees
WHERE SALARY >= 3000 AND SALARY <= 5000;

SELECT * FROM Employees
WHERE FIRST_NAME LIKE 'R%';

SELECT * FROM Employees
WHERE FIRST_NAME LIKE '_K%';

SELECT * FROM Employees
WHERE FIRST_NAME LIKE '%LY%';

SELECT * FROM Employees
WHERE FIRST_NAME NOT LIKE '%DA%';

SELECT * FROM Employees
WHERE COMMISSION_PCT = NULL;

SELECT * FROM Employees
WHERE COMMISSION_PCT IS NULL;

SELECT FIRST_NAME, UPPER(FIRST_NAME), LOWER(FIRST_NAME),
INITCAP(FIRST_NAME) FROM Employees;

SELECT * FROM Employees 
WHERE UPPER(LAST_NAME) = UPPER('%john%');

SELECT * FROM Employees 
WHERE UPPER(LAST_NAME) = UPPER('john');

SELECT LAST_NAME, LENGTH(LAST_NAME) FROM Employees
WHERE LENGTH(LAST_NAME) >= 6;

SELECT * FROM Employees;


SELECT EMAIL, SUBSTR(EMAIL, 3) FROM Employees;

SELECT EMAIL, SUBSTR(EMAIL, -LENGTH(EMAIL), 1) FROM Employees;

SELECT INSTR('hello this is oracle', 'c') AS INSTR FROM DUAL;

SELECT LAST_NAME FROM Employees WHERE INSTR(LAST_NAME, 'K')>0;

SELECT LAST_NAME FROM Employees WHERE LAST_NAME LIKE '%K%';

SELECT 'ASIA-AMERICA-EU' AS "BEFORE", REPLACE('ASIA-AMERICA-EU', '-', ' ') AS AFTER
FROM DUAL;

SELECT 'COFFEE', LPAD('COFFEE', 15, 'STARBUCKS') AS LPAD
FROM DUAL;

SELECT 'COFFEE', LPAD('COFFEE', 15, 'STARBUCKS') AS RPAD
FROM DUAL;

SELECT CONCAT(JOB_ID, CONCAT(' ', MANAGER_ID)) FROM Employees;

SELECT JOB_ID || ' ' || MANAGER_ID FROM Employees;