SELECT * FROM EMP
WHERE JOB NOT IN('MANAGER', 'SALESMAN', 'CLERK');

SELECT * FROM EMP
WHERE JOB != 'MANAGER' AND JOB <> 'SALESMAN' AND JOB ^= 'CLERK';

SELECT * FROM EMP
WHERE SAL >= 2000 AND SAL <= 3000; --BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE ENAME LIKE 'S%';

SELECT * FROM EMP
WHERE ENAME LIKE 'A%';

SELECT * FROM EMP
WHERE ENAME LIKE '_L%';

SELECT * FROM EMP
WHERE ENAME LIKE '%AM%';

SELECT * FROM EMP
WHERE ENAME NOT LIKE '%AM%';

SELECT * FROM EMP
WHERE COMM=NULL; --산술연산자와 비교 연산자 결과 값은 NULL

SELECT * FROM EMP
WHERE COMM IS NULL;