SELECT SYSDATE, SYSTIMESTAMP
FROM DUAL;

DESC EMP; --EMP --> EMPLOYEE 테이블

select sysdate, systimestamp from dual;

SELECT * FROM EMP; --EMP 테이블에 있는 모든 속성들의 인스턴스 조회
SELECT EMPNO, EANME, DEPTNO  
FROM EMP;

SELECT ALL JOB, DEPTNO
FROM EMP;

SELECT DISTINCT DEPTNO FROM EMP; --가져올 열이 1개, 중복 데이터 삭제

SELECT DISTINCT JOB, DEPTNO FROM EMP; -- 가져올 열이 여러 개, 중복 데이터 제거

SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL , COMM
FROM EMP;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
ORDER BY SAL;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
ORDER BY SAL DESC;

SELECT *
FROM EMP
ORDER BY DEPTNO ASC, SAL DESC;

SELECT *
FROM EMP
WHERE DEPTNO = 30;

SELECT * FROM EMP
WHERE DEPTNO=30 AND JOB="SALESMAN";

SELECT * FROM EMP
WHERE DEPTNO=30 OR JOB='CLERK';

SELECT * FROM EMP
WHERE SAL>=3000;

SELECT * FROM EMP
WHERE ENAME <='FORZ';

SELECT * FROM EMP
WHERE SAL != 3000;

SELECT * FROM EMP
WHERE SAL <> 3000;

SELECT * FROM EMP
WHERE NOT SAL = 3000;

